AWSTemplateFormatVersion: "2010-09-09"
Description: Template for creating AWS Glue databases, crawlers and IAM roles

Parameters:
  Stage:
    Type: String
    Description: Environment name (dev/qa/prod)
    AllowedValues: [dev, qa, prod]
  pBranchName:
    Description: "Branch Name(all lowercase, no symbols or spaces)"
    Type: String
  pArtifactsBucket:
    Description: "Artifact Bucket (all lowercase, no symbols or spaces)"
    Type: String
  pbucketAnalytics:
    Description: "Artifact Bucket (all lowercase, no symbols or spaces)"
    Type: String
  pAWSRegion:
    Description: "AWS region (all lowercase, no symbols or spaces)"
    Type: String
  pAWSAccountId:
    Description: "AWS account ID (all lowercase, no symbols or spaces)"
    Type: String
  pAWSAccountOpt:
    Description: "AWS account optimizador ID (all lowercase, no symbols or spaces)"
    Type: String
  pAccountName:
    Description: "AWS account name (all lowercase, no symbols or spaces)"
    Type: String
  pTeamName:
    Description: "Team Name (all lowercase, no symbols or spaces)"
    Type: String
  pdeploymentDate:
    Description: "Deployment date (all lowercase, no symbols or spaces)"
    Type: String
  pdbStageName:
    Description: "Database Stage name (all lowercase, no symbols or spaces)"
    Type: String
  pdbAnalyticsName:
    Description: "Database analytics name (all lowercase, no symbols or spaces)"
    Type: String
  pdeveloper:
    Description: "Database analytics name (all lowercase, no symbols or spaces)"
    Type: String
    Default: Josemaria_Paucar

Resources:
  MyGlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref pAWSAccountId
      DatabaseInput:
        Name: !Ref pdbStageName
        Description: !Sub "Base de datos en el catálogo de AWS Glue para el entorno ${Stage} (${pdbStageName})"
  
  analyticsDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref pAWSAccountId
      DatabaseInput:
        Name: !Ref pdbAnalyticsName
        Description: !Sub "Base de datos en el catálogo de AWS Glue para el entorno ${Stage} (${pdbAnalyticsName})"
  
  crawlerRoleAnalytics:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "role-${pTeamName}-crawler-${Stage}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "glue.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole'
      Policies:
        - PolicyName: "S3BucketAccessPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: 
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:ListBucket"
                Resource: 
                  - !Sub "arn:aws:s3:::${pTeamName}-${pAccountName}-analytics-${Stage}/*"
                  - !Sub "arn:aws:s3:::${pTeamName}-${pAccountName}-analytics-${Stage}"
  
  analyticsCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub "${pTeamName}-analytics-crawler-${Stage}"
      Role: !GetAtt crawlerRoleAnalytics.Arn
      DatabaseName: !Ref pdbAnalyticsName
      Targets:
        S3Targets:
          - Path: !Sub "s3://${pbucketAnalytics}"
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "LOG"
      Tags:
        Key1: "Value1"
      Schedule:
        ScheduleExpression: "cron(0 10 ? * * *)"
      Description: !Sub "Crawler to analyze data in ${pbucketAnalytics} bucket for ${Stage} environment"

  statisticsDbAnalitycsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "Role-${pTeamName}-statistics-db-Analytics"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GlueAndDynamoDBAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: GlueFullAccess
                Effect: Allow
                Action:
                  - glue:*
                  - s3:GetBucketLocation
                  - s3:ListBucket
                  - s3:ListAllMyBuckets
                  - s3:GetBucketAcl
                  - iam:ListRolePolicies
                  - iam:GetRole
                  - iam:GetRolePolicy
                  - cloudwatch:PutMetricData
                Resource: "*"
              - Sid: GlueS3Access
                Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                  - s3:GetBucketLocation
                Resource:
                  - arn:aws:s3:::aws-glue-*
                  - arn:aws:s3:::aws-glue-*/*
                  - arn:aws:s3:::crawler-public*
                  - arn:aws:s3:::stage-nelson-dev/*
              - Sid: GlueLogs
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*:/aws-glue/*
              - Sid: LakeFormationDataAccess
                Effect: Allow
                Action: lakeformation:GetDataAccess
                Resource: "*"
                Condition:
                  StringEquals:
                    aws:ResourceAccount: !Ref pAWSAccountId
              - Sid: IAMPassExecutionRole
                Effect: Allow
                Action:
                  - iam:PassRole
                Resource: 
                  - !Sub "arn:aws:iam::${pAWSAccountId}:role/service-role/Role-prueba-statistics-db-Analytics"
                Condition:
                  StringEquals:
                    iam:PassedToService: glue.amazonaws.com
              - Sid: DynamoDBAccess
                Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:BatchGetItem
                  - dynamodb:Scan
                  - dynamodb:Query
                  - dynamodb:DescribeTable
                Resource:
                  - !Sub "arn:aws:dynamodb:us-east-1:${pAWSAccountId}:table/table-prueba-statistics-db-Analytics"
                  - !Sub "arn:aws:dynamodb:us-east-1:${pAWSAccountId}:table/table-prueba-statistics-db-Analytics/index/*"
                Condition:
                  StringEquals:
                    aws:ResourceAccount: !Ref pAWSAccountId




  statisticsDbAnalitycsDynamo:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "table-${pTeamName}-statistics-db-Analytics"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: table_name
          AttributeType: S
        - AttributeName: database_name
          AttributeType: S
      KeySchema:
        - AttributeName: table_name
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: database_name
          KeySchema:
            - AttributeName: database_name
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: develop
          Value: !Ref pdeveloper

  statisticsDbAnalyticsLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: HolaMundoLambda
      Handler: index.handler
      Role: !GetAtt statisticsDbAnalitycsRole.Arn
      Runtime: python3.13
      Timeout: 900
      MemorySize: 2048
      Code:
        ZipFile: |
          import os

          def handler(event, context):
              desarrollador = os.getenv("DEVELOPER", "Desconocido")
              return {
                  "statusCode": 200,
                  "body": f"Hola mundo desde {desarrollador}"
              }
      Environment:
        Variables:
          DEVELOPER: !Ref pdeveloper
          Dynamo_TABLE: !Ref statisticsDbAnalitycsDynamo
      Tags:
        - Key: develop
          Value: !Ref pdeveloper


Outputs:
  StageDatabase:
    Description: "The Glue Database for stage data"
    Value: !Ref MyGlueDatabase
  AnalyticsDatabase:
    Description: "The Glue Database for analytics data"
    Value: !Ref analyticsDatabase
  CrawlerRole:
    Description: "IAM Role used by the Glue Crawler"
    Value: !Ref crawlerRoleAnalytics