AWSTemplateFormatVersion: "2010-09-09"
Description: Template for creating AWS Glue databases, crawlers and IAM roles

Parameters:
  Stage:
    Type: String
    Description: Environment name (dev/qa/prod)
    AllowedValues: [dev, qa, prod]
  pBranchName:
    Description: "Branch Name(all lowercase, no symbols or spaces)"
    Type: String
  pArtifactsBucket:
    Description: "Artifact Bucket (all lowercase, no symbols or spaces)"
    Type: String
  pbucketAnalytics:
    Description: "Artifact Bucket (all lowercase, no symbols or spaces)"
    Type: String
  pAWSRegion:
    Description: "AWS region (all lowercase, no symbols or spaces)"
    Type: String
  pAWSAccountId:
    Description: "AWS account ID (all lowercase, no symbols or spaces)"
    Type: String
  pAWSAccountOpt:
    Description: "AWS account optimizador ID (all lowercase, no symbols or spaces)"
    Type: String
  pAccountName:
    Description: "AWS account name (all lowercase, no symbols or spaces)"
    Type: String
  pTeamName:
    Description: "Team Name (all lowercase, no symbols or spaces)"
    Type: String
  pdeploymentDate:
    Description: "Deployment date (all lowercase, no symbols or spaces)"
    Type: String
  pdbStageName:
    Description: "Database Stage name (all lowercase, no symbols or spaces)"
    Type: String
  pdbAnalyticsName:
    Description: "Database analytics name (all lowercase, no symbols or spaces)"
    Type: String
  pdeveloper:
    Description: "Database analytics name (all lowercase, no symbols or spaces)"
    Type: String
    Default: Josemaria_Paucar

Resources:
  stageDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref pAWSAccountId
      DatabaseInput:
        Name: !Ref pdbStageName
        Description: !Sub "Base de datos en el catálogo de AWS Glue para el entorno ${Stage} (${pdbStageName})"
  
  analyticsDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref pAWSAccountId
      DatabaseInput:
        Name: !Ref pdbAnalyticsName
        Description: !Sub "Base de datos en el catálogo de AWS Glue para el entorno ${Stage} (${pdbAnalyticsName})"
  
  crawlerRoleAnalytics:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "role-${pTeamName}-crawler-${Stage}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "glue.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole'
      Policies:
        - PolicyName: "S3BucketAccessPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: 
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:ListBucket"
                Resource: 
                  - !Sub "arn:aws:s3:::${pTeamName}-${pAccountName}-analytics-${Stage}/*"
                  - !Sub "arn:aws:s3:::${pTeamName}-${pAccountName}-analytics-${Stage}"
  
  analyticsDbCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub "Glue-${pTeamName}-crawler-db-Analytics"
      Role: !GetAtt crawlerRoleAnalytics.Arn
      DatabaseName: !Ref pdbAnalyticsName
      Targets:
        S3Targets:
          - Path: !Sub "s3://${pbucketAnalytics}"
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "LOG"
      Tags:
        develop: !Ref pdeveloper
      Schedule:
        ScheduleExpression: "cron(0 10 ? * * *)"
      Description: !Sub "Crawler to analyze data in ${pbucketAnalytics} bucket for ${Stage} environment"
  
  statisticsDbAnalitycsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "Role-${pTeamName}-statistics-db-Analytics"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GlueServiceAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: GlueaccessCatalog
                Effect: Allow
                Action:
                  - glue:GetTable
                  - glue:GetTables
                  - glue:GetDatabase
                  - glue:GetDatabases
                  - glue:UpdateTable
                  - glue:GetTableVersions
                  - glue:StartJobRun
                  - glue:GetJobRun
                  - glue:GetJob
                  - glue:BatchGetJobs
                  - cloudwatch:PutMetricData
                  - glue:StartColumnStatisticsTaskRun
                Resource: 
                  - !Sub "arn:aws:iam::${pAWSAccountId}:role/Role-${pTeamName}-statistics-db-Analytics"
                  - !Sub "arn:aws:glue:${pAWSRegion}:${pAWSAccountId}:database/*"
                  - !Sub "arn:aws:glue:${pAWSRegion}:${pAWSAccountId}:table/*"
                  - !Sub "arn:aws:glue:${pAWSRegion}:${pAWSAccountId}:catalog*"
              - Sid: GlueS3Access
                Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:GetBucketLocation
                  - s3:ListBucket
                  - s3:GetBucketAcl
                Resource:
                  - arn:aws:s3:::aws-glue-*
                  - arn:aws:s3:::aws-glue-*/*
                  - arn:aws:s3:::crawler-public*
                  - !Sub "arn:aws:s3:::${pTeamName}-${pAccountName}-analytics-${Stage}/*"
                  - !Sub "arn:aws:s3:::${pTeamName}-${pAccountName}-analytics-${Stage}"
              - Sid: GlueLogs
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*:/aws-glue/*
              - Sid: LakeFormationDataAccess
                Effect: Allow
                Action: lakeformation:GetDataAccess
                Resource: "*"
                Condition:
                  StringEquals:
                    aws:ResourceAccount: ${pAWSAccountId}
              - Sid: IAMPassExecutionRole
                Effect: Allow
                Action: 
                  - iam:PassRole
                  - iam:ListRolePolicies
                  - iam:GetRole
                  - iam:GetRolePolicy
                Resource:
                  - !Sub "arn:aws:iam::${pAWSAccountId}:role/Role-${pTeamName}-statistics-db-Analytics"
                Condition:
                  StringEquals:
                    iam:PassedToService: glue.amazonaws.com
              - Sid: DynamoDBAccess
                Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:BatchGetItem
                  - dynamodb:Scan
                  - dynamodb:Query
                  - dynamodb:DescribeTable
                Resource:
                  - !Sub "arn:aws:dynamodb:us-east-1:${pAWSAccountId}:table/table-prueba-statistics-db-Analytics"
                  - !Sub "arn:aws:dynamodb:us-east-1:${pAWSAccountId}:table/table-prueba-statistics-db-Analytics/index/*"
                Condition:
                  StringEquals:
                    aws:ResourceAccount: !Ref pAWSAccountId

  statisticsDbAnalitycsDynamo:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "table-${pTeamName}-statistics-db-Analytics"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: Table_name
          AttributeType: S
        - AttributeName: DatabaseName
          AttributeType: S
      KeySchema:
        - AttributeName: Table_name
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: DatabaseName
          KeySchema:
            - AttributeName: DatabaseName
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: develop
          Value: !Ref pdeveloper

  statisticsDbAnalyticsLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "lambda-${pTeamName}-statistics-db-Analytics"
      Handler: lambda_function.lambda_handler
      Role: !GetAtt statisticsDbAnalitycsRole.Arn
      Runtime: python3.11
      Timeout: 180
      MemorySize: 512
      Code:
        ZipFile: |
          import os

          def handler(event, context):
              desarrollador = os.getenv("DEVELOPER", "Desconocido")
              return {
                  "statusCode": 200,
                  "body": f"Hola mundo desde {desarrollador}"
              }
      Environment:
        Variables:
          DYNAMO_TABLE: !Ref statisticsDbAnalitycsDynamo
          IAM_ROLE: !Ref statisticsDbAnalitycsRole
          ACCOUNT_ID: !Ref pAWSAccountId
      Tags:
        - Key: develop
          Value: !Ref pdeveloper

  statisticsDbAnalyticsLambdaEventRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: "cron(0 11 * * ? *)" 
      State: "ENABLED"
      Targets:
        - Id: !Sub "Eventrule-${pTeamName}-statistics-db-Analytics"
          Arn: !Sub "arn:aws:lambda:us-east-1:${pAWSAccountId}:function:lambda-${pTeamName}-statistics-db-Analytics"
  

Outputs:
  StageDatabase:
    Description: "The Glue Database for stage data"
    Value: !Ref stageDatabase
  AnalyticsDatabase:
    Description: "The Glue Database for analytics data"
    Value: !Ref analyticsDatabase