AWSTemplateFormatVersion: "2010-09-09"
Description: template para crear roles y políticas IAM

Parameters:
  Stage:
    Type: String
    Description: Environment name (dev/qa/prod)
    Default: dev
  pBranchName:
    Description: "Branch Name(all lowercase, no symbols or spaces)"
    Type: String
  pArtifactsBucket:
    Description: "Artifact Bucket (all lowercase, no symbols or spaces)"
    Type: String
  pAWSRegion:
    Description: "Aws region (all lowercase, no symbols or spaces)"
    Type: String
  pAWSAccountId:
    Description: "Aws account (all lowercase, no symbols or spaces)"
    Type: String
  pAWSAccountOptId:
    Description: "Aws account optimizador Id(all lowercase, no symbols or spaces)"
    Type: String
  pAccountName:
    Description: "Aws account (all lowercase, no symbols or spaces)"
    Type: String
  pTeamName:
    Description: "Aws account (all lowercase, no symbols or spaces)"
    Type: String
  pdeploymentDate:
    Description: "Aws account (all lowercase, no symbols or spaces)"
    Type: String

Resources:

  S3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: stage-nelson-dev
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AccessAccountDatalakeObjectDataSyncs"
            Effect: "Allow"
            Principal:
              AWS:
                - !Sub "arn:aws:iam::${pAWSAccountId}:root"
                - !Sub "arn:aws:iam::${pAWSAccountId}:role/role-${pTeamName}-datasync-${Stage}"
            Action:
              - "s3:GetBucketLocation"
              - "s3:ListBucket"
              - "s3:ListBucketMultipartUploads"
              - "s3:AbortMultipartUpload"
              - "s3:DeleteObject"
              - "s3:GetObject"  
              - "s3:ListMultipartUploadParts"
              - "s3:PutObjectTagging"
              - "s3:GetObjectTagging"
              - "s3:PutObject"
            Resource:
              - !Sub "arn:aws:s3:::stage-nelson-dev"
              - !Sub "arn:aws:s3:::stage-nelson-dev/*"  

  
  DataSyncS3LocationOptimizador:
    Type: AWS::DataSync::LocationS3
    Properties:
      S3BucketArn: !Sub "arn:aws:s3:::stage-yvoone-${Stage}"
      S3Config:
        BucketAccessRoleArn: !Sub "arn:aws:iam::${pAWSAccountId}:role/role-${pTeamName}-datasync-${Stage}"
      Subdirectory: "/regional/optimizador/rg_in_optimizador_stage/"
  
  DataSyncDestinationLocationOptimizador:
    Type: AWS::DataSync::LocationS3
    Properties:
      S3BucketArn: !Sub "arn:aws:s3:::stage-nelson-${Stage}"
      S3Config:
        BucketAccessRoleArn: !Sub "arn:aws:iam::${pAWSAccountId}:role/role-${pTeamName}-datasync-${Stage}"
      Subdirectory: "/regional/externa/rg_in_optimizador_stage/"
  
  DataSyncTaskEjecOptimizador:
    Type: AWS::DataSync::Task
    Properties:
      Name: !Sub "Optimizador_${Stage}-Ecodistribucion_${Stage}-Optimizador-diario"
      SourceLocationArn: !Ref DataSyncS3LocationOptimizador
      DestinationLocationArn: !Ref DataSyncDestinationLocationOptimizador
      Options:
        VerifyMode: "ONLY_FILES_TRANSFERRED"
        OverwriteMode: "ALWAYS"
        TransferMode: "CHANGED"
      Includes:
        - FilterType: "SIMPLE_PATTERN"
          Value: "/year=*"
      Schedule:
        ScheduleExpression: "cron(30 17-23/2,1,3,5 * * ? *)"
