AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Stage:
    Type: String
    Description: Environment name (dev/qa/prod)
    Default: dev
  pBranchName:
    Description: "Branch Name(all lowercase, no symbols or spaces)"
    Type: String
  pArtifactsBucket:
    Description: "Artifact Bucket (all lowercase, no symbols or spaces)"
    Type: String
  pAWSRegion:
    Description: "Aws region (all lowercase, no symbols or spaces)"
    Type: String
  pAWSAccountId:
    Description: "Aws account (all lowercase, no symbols or spaces)"
    Type: String
  pAWSAccountOptId:
    Description: "Aws account optimizador Id(all lowercase, no symbols or spaces)"
    Type: String
  pAccountName:
    Description: "Aws account (all lowercase, no symbols or spaces)"
    Type: String
  pTeamName:
    Description: "Aws account (all lowercase, no symbols or spaces)"
    Type: String
  pdeploymentDate:
    Description: "Aws account (all lowercase, no symbols or spaces)"
    Type: String

Resources:
  MyEventRule:
      Type: AWS::Events::Rule
      Properties:
        ScheduleExpression: "cron(0 12 * * ? *)" # Cambia según la frecuencia que necesites
        State: "ENABLED"
        Targets:
          - Id: "MyLambdaTarget"
            Arn: "arn:aws:lambda:us-east-1:039612881651:function:function-dev-prueba"



  S3CreateObjectRule:
    Type: AWS::Events::Rule
    Properties:
      Name: S3CreateObjectEventRuleprueba
      Description: "Regla que captura eventos de creación de objetos en S3 y activa una función Lambda."
      EventPattern:
        source:
          - "aws.s3"
        detail-type:
          - "AWS API Call via CloudTrail"
        detail:
          eventSource:
            - "s3.amazonaws.com"
          eventName:
            - "PutObject"
            - "CompleteMultipartUpload"
          requestParameters:
            bucketName:
              - "koa-prueba-345345345345"
      State: ENABLED
      Targets:
        - Id: LambdaTarget
          Arn: arn:aws:lambda:us-east-1:039612881651:function:lambda-example-Josemaria-api_Misupply



  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: arn:aws:lambda:us-east-1:039612881651:function:lambda-example-Josemaria-api_Misupply
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt S3CreateObjectRule.Arn
Outputs: 
  MyEventRule:
    Description: MyEventRule Arn
    Value: !GetAtt MyEventRule.Arn
    Export:
      Name: DA-MyEventRule
