AWSTemplateFormatVersion: "2010-09-09"
Description: template para crear roles y políticas IAM

Parameters:
  Stage:
    Type: String
    Description: Environment name (dev/qa/prod)
    Default: dev
  pBranchName:
    Description: "Branch Name(all lowercase, no symbols or spaces)"
    Type: String
  pArtifactsBucket:
    Description: "Artifact Bucket (all lowercase, no symbols or spaces)"
    Type: String
  pAWSRegion:
    Description: "Aws region (all lowercase, no symbols or spaces)"
    Type: String
  pAWSAccountId:
    Description: "Aws account (all lowercase, no symbols or spaces)"
    Type: String
  pAWSAccountOptId:
    Description: "Aws account optimizador Id(all lowercase, no symbols or spaces)"
    Type: String
  pAccountName:
    Description: "Aws account (all lowercase, no symbols or spaces)"
    Type: String
  pTeamName:
    Description: "Aws account (all lowercase, no symbols or spaces)"
    Type: String
  pdeploymentDate:
    Description: "Aws account (all lowercase, no symbols or spaces)"
    Type: String

Resources:

  DataSyncRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "role-${pTeamName}-datasync-${Stage}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "datasync.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole"
        - "arn:aws:iam::aws:policy/AmazonSNSFullAccess"
      MaxSessionDuration: 3600
      Path: "/"
      Policies:
        - PolicyName: !Sub "${pTeamName}-access-to-s3-policy-bucketStage"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: AccessToS3Bucket
                Effect: "Allow"
                Action:
                  - "s3:GetBucketLocation"
                  - "s3:ListBucket"
                  - "s3:GetObject"
                Resource: !Sub "arn:aws:s3:::stage-yvoone-${Stage}"
              - Sid: AccessToS3Objects
                Effect: "Allow"
                Action:
                  - "s3:AbortMultipartUpload"
                  - "s3:GetObject"
                  - "s3:ListMultipartUploadParts"
                  - "s3:PutObject"
                  - "s3:GetObjectTagging"
                  - "s3:ListBucket"
                  - "s3:PutObjectTagging"
                Resource: !Sub "arn:aws:s3:::stage-yvoone-${Stage}/*"
                 

  lambdaMisupplyApiRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "role-${pTeamName}-misupplyapi-${Stage}"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole"
        - "arn:aws:iam::aws:policy/AmazonSNSFullAccess"
        - "arn:aws:iam::aws:policy/AmazonAthenaFullAccess"
        - "arn:aws:iam::aws:policy/SecretsManagerReadWrite"
        - "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
        - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
      MaxSessionDuration: 43200
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "glue.amazonaws.com"
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: !Sub "${pTeamName}-${pAccountName}-access-to-s3-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: AccessToS3Policy
                Effect: Allow
                Action: s3:*
                Resource:
                  - !Sub "arn:aws:s3:::stage-nelson-${Stage}/*"
              - Sid: ReadSecretsManager
                Effect: Allow
                Action:
                  - "secretsmanager:GetSecretValue"
                  - "secretsmanager:DescribeSecret"
                  - "secretsmanager:ListSecrets"
                Resource:
                  - !Sub "arn:aws:secretsmanager:${pAWSRegion}:${pAWSAccountId}:secret:*"
  S3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: stage-nelson-dev
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AccessAccountDatalakeObjectDataSyncs"
            Effect: "Allow"
            Principal:
              AWS:
                - !Sub "arn:aws:iam::${pAWSAccountId}:root"
                - !Sub "arn:aws:iam::${pAWSAccountId}:role/role-${pTeamName}-datasync-${Stage}"
            Action:
              - "s3:GetBucketLocation"
              - "s3:ListBucket"
              - "s3:ListBucketMultipartUploads"
              - "s3:AbortMultipartUpload"
              - "s3:DeleteObject"
              - "s3:ListMultipartUploadParts"
              - "s3:PutObjectTagging"
              - "s3:GetObjectTagging"
              - "s3:PutObject"
            Resource:
              - !Sub "arn:aws:s3:::stage-nelson-dev"
              - !Sub "arn:aws:s3:::stage-nelson-dev/*"  

Outputs:
  lambdaMisupplyApiRole:
    Description: lambdaMisupplyApiRole Arn
    Value: !GetAtt lambdaMisupplyApiRole.Arn
    Export:
      Name: lambdaMisupplyApiRole-Arn
