AWSTemplateFormatVersion: "2010-09-09"
Description: Template for creating AWS Iam

Parameters:
  Stage:
    Type: String
    Description: Environment name (dev/qa/prod)
    AllowedValues: [dev, qa, prod]
  pBranchName:
    Description: "Branch Name(all lowercase, no symbols or spaces)"
    Type: String
  pArtifactsBucket:
    Description: "Artifact Bucket (all lowercase, no symbols or spaces)"
    Type: String
  pbucketAnalytics:
    Description: "Artifact Bucket (all lowercase, no symbols or spaces)"
    Type: String
  pAWSRegion:
    Description: "AWS region (all lowercase, no symbols or spaces)"
    Type: String
  pAWSAccountId:
    Description: "AWS account ID (all lowercase, no symbols or spaces)"
    Type: String
  pAWSAccountOpt:
    Description: "AWS account optimizador ID (all lowercase, no symbols or spaces)"
    Type: String
  pAccountName:
    Description: "AWS account name (all lowercase, no symbols or spaces)"
    Type: String
  pTeamName:
    Description: "Team Name (all lowercase, no symbols or spaces)"
    Type: String
  pdeploymentDate:
    Description: "Deployment date (all lowercase, no symbols or spaces)"
    Type: String
  pdbStageName:
    Description: "Database Stage name (all lowercase, no symbols or spaces)"
    Type: String
  pdbAnalyticsName:
    Description: "Database analytics name (all lowercase, no symbols or spaces)"
    Type: String
  pdeveloper:
    Description: "Database analytics name (all lowercase, no symbols or spaces)"
    Type: String
    Default: Josemaria_Paucar
  pRDAWSAccountId:
    Description: "Account Ruta Digital (all lowercase, no symbols or spaces)"
    Type: String
  # Country parameters
  pCountryCl:
    Description: "Country code for Chile"
    Type: String
    Default: "cl"
  pCountryPy:
    Description: "Country code for Paraguay"
    Type: String
    Default: "py"
  pCountryAr:
    Description: "Country code for Argentina"
    Type: String
    Default: "ar"
  pCountryBr:
    Description: "Country code for Brazil"
    Type: String
    Default: "br"
  pCountryRg:
    Description: "Country code for Regional"
    Type: String
    Default: "rg"
  # Required for referenced resources

Resources:

  dataSyncOptimizadorRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "role-${pTeamName}-datasync-${pCountryRg}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "datasync.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole"
      MaxSessionDuration: 3600
      Path: "/"
      Policies:
        - PolicyName: !Sub "${pTeamName}-access-to-s3-policy-bucketStage"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: AccessToS3Bucket
                Effect: "Allow"
                Action:
                  - "s3:GetBucketLocation"
                  - "s3:ListBucket"
                Resource:
                  - !Sub "arn:aws:s3:::prueba-josemaria-analytics-dev"
                  - !Sub "arn:aws:s3:::stage-datalake-josemaria"
              - Sid: AccessToS3Objects
                Effect: "Allow"
                Action:
                  - "s3:AbortMultipartUpload"
                  - "s3:GetObject"
                  - "s3:ListMultipartUploadParts"
                  - "s3:PutObject"
                  - "s3:GetObjectTagging"
                  - "s3:ListBucket"
                  - "s3:PutObjectTagging"
                  - "s3:DeleteObject"
                Resource: 
                  - !Sub "arn:aws:s3:::josemaria-s3-prueba-dev"
                  - !Sub "arn:aws:s3:::stage-datalake-josemaria"
