AWSTemplateFormatVersion: "2010-09-09"
Description: template para crear roles y políticas IAM

Parameters:
  Stage:
    Type: String
    Description: Environment name (dev/qa/prod)
    Default: dev
  pBranchName:
    Description: "Branch Name(all lowercase, no symbols or spaces)"
    Type: String
  pArtifactsBucket:
    Description: "Artifact Bucket (all lowercase, no symbols or spaces)"
    Type: String
  pAWSRegion:
    Description: "Aws region (all lowercase, no symbols or spaces)"
    Type: String
  pAWSAccountId:
    Description: "Aws account (all lowercase, no symbols or spaces)"
    Type: String
  pAWSAccountOptId:
    Description: "Aws account optimizador Id(all lowercase, no symbols or spaces)"
    Type: String
  pAccountName:
    Description: "Aws account (all lowercase, no symbols or spaces)"
    Type: String
  pTeamName:
    Description: "Aws account (all lowercase, no symbols or spaces)"
    Type: String
  pdeploymentDate:
    Description: "Aws account (all lowercase, no symbols or spaces)"
    Type: String

Resources:

  DataSyncRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "role-${pTeamName}-datasync-${Stage}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "datasync.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole"
        - "arn:aws:iam::aws:policy/AmazonSNSFullAccess"
      MaxSessionDuration: 3600
      Path: "/"
      Policies:
        - PolicyName: !Sub "${pTeamName}-access-to-s3-policy-bucketStage"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: AccessToS3Bucket
                Effect: "Allow"
                Action:
                  - "s3:GetBucketLocation"
                  - "s3:ListBucket"
                Resource: !Sub "arn:aws:s3:::stage-nelson-${Stage}"
              - Sid: AccessToS3Objects
                Effect: "Allow"
                Action:
                  - "s3:AbortMultipartUpload"
                  - "s3:GetObject"
                  - "s3:ListMultipartUploadParts"
                  - "s3:PutObject"
                  - "s3:GetObjectTagging"
                  - "s3:ListBucket"
                  - "s3:PutObjectTagging"
                Resource: !Sub "arn:aws:s3:::stage-nelson-${Stage}/*"
                 


