AWSTemplateFormatVersion: "2010-09-09"
Description: Template for creating AWS Proyecto NPS

Parameters:
  Stage:
    Type: String
    Description: Environment name (dev/qa/prod)
    AllowedValues: [dev, qa, prod]
  pBranchName:
    Description: "Branch Name(all lowercase, no symbols or spaces)"
    Type: String
  pArtifactsBucket:
    Description: "Artifact Bucket (all lowercase, no symbols or spaces)"
    Type: String
  pbucketAnalytics:
    Description: "Artifact Bucket (all lowercase, no symbols or spaces)"
    Type: String
  pAWSRegion:
    Description: "AWS region (all lowercase, no symbols or spaces)"
    Type: String
  pAWSAccountId:
    Description: "AWS account ID (all lowercase, no symbols or spaces)"
    Type: String
  pAWSAccountOpt:
    Description: "AWS account optimizador ID (all lowercase, no symbols or spaces)"
    Type: String
  pAccountName:
    Description: "AWS account name (all lowercase, no symbols or spaces)"
    Type: String
  pTeamName:
    Description: "Team Name (all lowercase, no symbols or spaces)"
    Type: String
  pdeploymentDate:
    Description: "Deployment date (all lowercase, no symbols or spaces)"
    Type: String
  pdbStageName:
    Description: "Database Stage name (all lowercase, no symbols or spaces)"
    Type: String
  pdbAnalyticsName:
    Description: "Database analytics name (all lowercase, no symbols or spaces)"
    Type: String
  pdeveloper:
    Description: "Database analytics name (all lowercase, no symbols or spaces)"
    Type: String
    Default: Josemaria_Paucar
  pRDAWSAccountId:
    Description: "Account Ruta Digital (all lowercase, no symbols or spaces)"
    Type: String
  # Country parameters
  pCountryCl:
    Description: "Country code for Chile"
    Type: String
    Default: "cl"
  pCountryPy:
    Description: "Country code for Paraguay"
    Type: String
    Default: "py"
  pCountryAr:
    Description: "Country code for Argentina"
    Type: String
    Default: "ar"
  pCountryBr:
    Description: "Country code for Brazil"
    Type: String
    Default: "br"
  pCountryRg:
    Description: "Country code for Regional"
    Type: String
    Default: "rg"
  # Required for referenced resources

Resources:
  npsFeedbackRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "role-${pTeamName}-nps-feedback-${pCountryCl}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !GetAtt npsFeedbackCLDynamo.Arn
                  - !Sub "${npsFeedbackCLDynamo.Arn}/index/*"
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub "arn:aws:s3:::${pbucketAnalytics}/*"
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !Sub "arn:aws:s3:::${pbucketAnalytics}"
      Tags:
        - Key: develop
          Value: !Ref pdeveloper

  npsFeedbackCLDynamo:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "table-${pTeamName}-nps-feedback-${pCountryCl}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: Truck
          AttributeType: S
        - AttributeName: Execution_date
          AttributeType: S
      KeySchema:
        - AttributeName: Truck
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: Execution_date
          KeySchema:
            - AttributeName: Execution_date
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: develop
          Value: !Ref pdeveloper

  consolidadoNpsFeedbackCLLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "Lambda-${pTeamName}-nps-feedback-consolidado-${pCountryCl}"
      Handler: lambda_function.lambda_handler
      Role: !GetAtt npsFeedbackRole.Arn
      Runtime: python3.13
      Timeout: 900
      MemorySize: 2048
      Code:
        ZipFile: |
          import os

          def handler(event, context):
              desarrollador = os.getenv("DEVELOPER", "Desconocido")
              return {
                  "statusCode": 200,
                  "body": f"Hola mundo desde {desarrollador}"
              }
      Environment:
        Variables:
          DYNAMO_TABLE: !Ref npsFeedbackCLDynamo
          ACCOUNT_ID: !Ref pAWSAccountId
      Tags:
        - Key: develop
          Value: !Ref pdeveloper
  
  rtNpsFeedbackCLLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "Lambda-${pTeamName}-nps-feedback-rt-${pCountryCl}"
      Handler: lambda_function.lambda_handler
      Role: !GetAtt npsFeedbackRole.Arn
      Runtime: python3.13
      Timeout: 900
      MemorySize: 2048
      Code:
        ZipFile: |
          import os

          def handler(event, context):
              desarrollador = os.getenv("DEVELOPER", "Desconocido")
              return {
                  "statusCode": 200,
                  "body": f"Hola mundo desde {desarrollador}"
              }
      Environment:
        Variables:
          DYNAMO_TABLE: !Ref npsFeedbackCLDynamo
          ACCOUNT_ID: !Ref pAWSAccountId
      Tags:
        - Key: develop
          Value: !Ref pdeveloper

  rtNpsFeedbackCLLambdaPn:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt rtNpsFeedbackCLLambda.Arn
      Action: "lambda:InvokeFunction"
      Principal: !Sub "arn:aws:iam::${pRDAWSAccountId}:root"
      SourceAccount: !Ref pRDAWSAccountId

  npsFeedbackClEventRule:
      Type: AWS::Events::Rule
      Properties:
        ScheduleExpression: "cron(0 7 * * ? *)" 
        State: "ENABLED"
        Targets:
          - Id: !Sub "Eventrule-${pTeamName}-nps-feedback"
            Arn: !Sub "arn:aws:lambda:us-east-1:${pAWSAccountId}:function:Lambda-${pTeamName}-nps-feedback-consolidado-${pCountryCl}"
  
