name: CloudFormation deploy

on:
  pull_request:
    types: [closed]
    branches: [develop, qa, prod]


jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.base_ref }}
    
    permissions:
      id-token: write
      contents: read
      pull-requests: write

      env:
      ENVIRONMENT: ${{ github.base_ref == 'develop' && 'dev' || github.base_ref }}
      REGION: "us-east-1"
      TIMESTAMP: ${{ format('{0:yyyyMMddHHmmss}', github.event.pull_request.merged_at) }}

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set parameters and tags files
        run: |
          echo "PARAMETERS_FILE=./parameters-$ENVIRONMENT.json" >> $GITHUB_ENV
          echo "PARAMETERS_TAG=./tags-$ENVIRONMENT.json" >> $GITHUB_ENV
      

      - name: Load JSON into Environment Variables
        run: |
          for row in $(jq -c '.[]' $PARAMETERS_FILE); do
            key=$(echo $row | jq -r 'keys[0]')
            value=$(echo $row | jq -r '.[]')
            echo "${key}=${value}" >> $GITHUB_ENV
          done
          echo "Loaded variables from $PARAMETERS_FILE."
      
      - name: Process Tags
        run: |
          TAGS=$(jq -r 'map("\(.Key)=\(.Value|gsub(" "; "_")|gsub("&"; "and"))") | join(" ")' $PARAMETERS_TAG)
          echo "TAGS=${TAGS}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          role-session-name: pruebarolesession
          aws-region: ${{ env.REGION }}
      
      # Define common CloudFormation parameters
      - name: Set common parameters
        run: |
          echo "COMMON_PARAMS=pTeamName=$TEAM Stage=$ENVIRONMENT pBranchName=$BRANCH_NAME pArtifactsBucket=$ARTIFACTORY_BUCKET pAWSRegion=$REGION pAWSAccountId=$AWS_ACCOUNT_ID pAWSAccountOpt=$AWS_ACCOUNT_ID_OPT pdbStageName=$DB_STAGE pAccountName=$AWS_ACCOUNT pdeploymentDate=$TIMESTAMP" >> $GITHUB_ENV

      
      # Create a reusable deployment function
      - name: Define deployment function
        run: |
          function deploy_stack() {
            local template=$1
            local stack_name=$2
            local extra_params="${3:-}"

            echo "Deploying $stack_name using $template"
            aws cloudformation deploy \
              --template-file templates/$template \
              --region $REGION \
              --stack-name $stack_name \
              --capabilities CAPABILITY_NAMED_IAM \
              --no-fail-on-empty-changeset \
              --tags $TAGS \
              --parameter-overrides \
                $COMMON_PARAMS \
                $extra_params

            aws cloudformation describe-stack-events --stack-name $stack_name --max-items 5 --output table
          }
          echo "function deploy_stack() { $(declare -f deploy_stack | tail -n +2)" >> $GITHUB_ENV


      # Deploy resources based on PR title
      - name: Deploy IAM
        if: contains(github.event.pull_request.title, '-iam') || contains(github.event.pull_request.title, '-all')
        run: deploy_stack "iam.yaml" "da-josemaria-iam" "pRDAWSAccountId=$AWS_RUTADIGITAL_ID"

      - name: Deploy S3
        if: contains(github.event.pull_request.title, '-s3')
        run: deploy_stack "s3.yaml" "da-josemaria-s3" "ArtifactsBucket=$ARTIFACTORY_BUCKET"

      # Layer upload section
      - name: Upload layers to S3
        if: contains(github.event.pull_request.title, '-layer')
        run: |
          aws s3 cp ./layers/awswrangler-layer-py3-9.zip s3://$ARTIFACTORY_BUCKET/layers/
          aws s3 cp ./layers/request-layer-py3-12.zip s3://$ARTIFACTORY_BUCKET/layers/

      # Other resources
      - name: Deploy Layers
        if: contains(github.event.pull_request.title, '-layers') || contains(github.event.pull_request.title, '-all')
        run: deploy_stack "layers.yaml" "da-josemaria-layers" "pRDAWSAccountId=$AWS_RUTADIGITAL_ID"

      - name: Deploy CATALOGO ATHENA DB
        if: contains(github.event.pull_request.title, '-athenacatalogo') || contains(github.event.pull_request.title, '-all')
        run: deploy_stack "athenacatalogo.yaml" "da-josemaria-athenacatalogo" "pdbAnalyticsName=$DB_ANALYTICS"

      # Remaining stack deployments
      - name: Deploy remaining stacks
        run: |
          if [[ "${{ contains(github.event.pull_request.title, '-koa-da-josemaria-eta') || contains(github.event.pull_request.title, '-all') }}" == "true" ]]; then
            deploy_stack "koa-da-josemaria-eta.yaml" "koa-da-josemaria-eta"
          fi

          if [[ "${{ contains(github.event.pull_request.title, '-koa-da-josemaria-misupply') || contains(github.event.pull_request.title, '-all') }}" == "true" ]]; then
            deploy_stack "koa-da-josemaria-misupply.yaml" "koa-da-josemaria-misupply"
          fi

          if [[ "${{ contains(github.event.pull_request.title, '-koa-da-josemaria-nps-feedback') || contains(github.event.pull_request.title, '-all') }}" == "true" ]]; then
            deploy_stack "koa-da-josemaria-nps-feedback.yaml" "koa-da-josemaria-nps-feedback"
          fi

          if [[ "${{ contains(github.event.pull_request.title, '-koa-da-josemaria-optimizador') || contains(github.event.pull_request.title, '-all') }}" == "true" ]]; then
            deploy_stack "koa-da-josemaria-optimizador.yaml" "koa-da-josemaria-optimizador"
          fi



      